version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"   # React frontend
      - "80:80"       # Node server
      - "5001:5000"   # Flask backend
    env_file:
      - .env
    environment:
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
