version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - .env  # Loads environment variables if any are needed in frontend

  server:
    build:
      context: ./server
    ports:
      - "80:80"
    env_file:
      - .env  # Loads environment variables like PostgreSQL credentials
    depends_on:
      - flaskapp
    environment:
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
      - PORT=${PORT}

  flaskapp:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    env_file:
      - .env  # Loads OpenAI API key for Flask app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
